###test-grupos

GET http://localhost:8888/index.php/grupo HTTP/1.1

###

DELETE http://localhost:8888/index.php/grupo/11 HTTP/1.1


###

POST http://localhost:8888/index.php/grupo HTTP/1.1
Content-Type: application/json

{
    "grupNombre":"Camionetas",
    "grupDescripcion":"Camionetas HIlux modelo 2020"
}

###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
    "grupId": 12,
    "grupNombre": "Camionetas",
    "grupDescripcion": "Camionetas hilux modelo new"
}

###test-servicio


GET http://localhost:8888/index.php/servicio HTTP/1.1

###

DELETE http://localhost:8888/index.php/servicio/5 HTTP/1.1


###

POST http://localhost:8888/index.php/servicio HTTP/1.1
Content-Type: application/json

{
    "servNombre":"motor",
    "servDescripcion":"verificar motor",
    "servPeriodo": 70,
    "servKM": 15000,
    "servFecha": 0
}

###

PUT http://localhost:8888/index.php/servicio HTTP/1.1

{
    "servNombre": "ruedas",
    "servDescripcion": "verificar ruedas",
    "servPeriodo": 80,
    "servKM": 15000,
    "servFecha": 0,
    "servId": 9
}


###test-tarea


GET http://localhost:8888/index.php/tarea HTTP/1.1


###

DELETE http://localhost:8888/index.php/tarea/8 HTTP/1.1


###

POST http://localhost:8888/index.php/tarea HTTP/1.1
Content-Type: application/json

{
    "tareNombre": "cambio de aceite",
    "tareDescripcion": "cambiar el aceite del vehiculo",
    "tareUnidadMedida": "ml",
    "tareCantidad": 1,
    "tareCosto": 11
}

###

PUT http://localhost:8888/index.php/tarea HTTP/1.1

{
    "tareNombre": "xx",
    "tareDescripcion": "xx",
    "tareUnidadMedida": "ml",
    "tareCantidad": 1,
    "tareCosto": 11,
    "tareId":7
}

###test-servicio-tarea


GET http://localhost:8888/index.php/servicio-tarea HTTP/1.1


###


GET http://localhost:8888/index.php/servicio-tarea HTTP/1.1


###

DELETE http://localhost:8888/index.php/servicio-tarea/1 HTTP/1.1


###

POST http://localhost:8888/index.php/servicio-tarea HTTP/1.1
Content-Type: application/json

{
    "setaServId":7,
    "setaTareId":1,
}

###

PUT http://localhost:8888/index.php/servicio-tarea HTTP/1.1

{
    "setaServId":2,
    "setaTareId":1,
    "setaId": 15
    
}


### grupo-servicio


GET http://localhost:8888/index.php/grupo-servicio HTTP/1.1


###

DELETE http://localhost:8888/index.php/grupo-servicio/48 HTTP/1.1


###

POST http://localhost:8888/index.php/grupo-servicio HTTP/1.1
Content-Type: application/json

{
    "grusGrupId": 1,
    "grusServId": 1,
    "grusPeriodo": 1,
    "grusKm":1,
    "grusFecha": 1 
}

###

PUT http://localhost:8888/index.php/grupo-servicio HTTP/1.1

{
    "grusGrupId": 38,
    "grusServId": 9,
    "grusPeriodo": 2,
    "grusKm":4,
    "grusFecha": 0,
    "grusId": 61
    
}